version : '3.6'
services : 
  tilawati-api : 
    build : ./ 
    # entrypoint : /tmp/run.sh
    # command : adonis serve --dev
    working_dir : /usr/src/tilawati
    depends_on : 
      - mysql
    ports : 
      - "3333:3333"
    volumes : 
      - ./:/usr/src/tilawati 
      - /usr/src/tilawati/node_modules/
    networks:
      - api_db 
  mysql :
    image : mysql
    entrypoint : /usr/src/tilawati/db.sh
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment : 
      MYSQL_ROOT_PASSWORD: abdelkhalek
      MYSQL_DATABASE: tilawati
    ports : 
      - "3307:3306"
    networks:
      - api_db 
networks:
  api_db :
    driver: bridge
